author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 以下配置为签到
  # 这里默认仅适配武汉船舶职业技术学院，其他学校自行修改
  - user: # 俺自己
      name: 徐铭宇
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182644'
      #password 密码
      password: 'a2776110625'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '2776110625@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
              title: 早测温
              value: 37.3度以下
        - form:
              title: 午测温
              value: 37.3度以下
        - form:
              title: 晚测温
              value: 37.3度以下
        - form:
              title: 健康状况
              value: 健康
  - user: # 柳建慧
      name: '柳建慧'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20183191'
      #password 密码
      password: 'q2511030166'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign2.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 沈羿辉
      name: '沈羿辉'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20190021'
      #password 密码
      password: 'Qaz112233'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign3.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 郭永帅
      name: '郭永帅'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20203862'
      #password 密码
      password: 'gys123456'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign4.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 李佩洋
      name: '李佩洋'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20192308'
      #password 密码
      password: '20192308l'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '2055998171@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign5.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 冯志超
      name: '冯志超'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20203703'
      #password 密码
      password: '2024kyjy'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '2507540878@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign6.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 黄洋
      name: '黄洋'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20192223'
      #password 密码
      password: 'Hy001002'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign7.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 付博悦
      name: '付博悦'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20192297'
      #password 密码
      password: 'by010719.'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign8.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user: # 邵晨
      name: '邵晨'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20192236'
      #password 密码
      password: 'Scipad@8097'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '2016295189@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign9.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user:
      name: '张依林'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182650'
      #password 密码
      password: 'z12345'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '3276586184@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign10.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user:
      name: '彭奇'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20203877'
      #password 密码
      password: 'pq010410'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '2437373602@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign11.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user:
      name: '李馥竹'
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20203826'
      #password 密码
      password: 'lfz022427'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区奋进乡地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '1062990234@qq.com'
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.397156
      #lat 纬度
      lat: 44.003724
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign12.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
