name: Upload Python Package

on:
  repository_dispatch:
  schedule:
    - cron: '22 12 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  Auto-Attendance:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git subversion git-core python3-pip
          sudo timedatectl set-timezone "$TZ"

      - name: Clone and SetUp pip
        run: |
          echo 'start clone'
          git clone https://github.com/ScottDemo/fuckTodayStudy.git --depth=1
          cd fuckTodayStudy
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
          python3 index.py
      - name: Last Run
        run: 
          echo 'start running'
          mv $GITHUB_WORKSPACE/config.yml $GITHUB_WORKSPACE/fuckTodayStudy/config.yml
          cd $GITHUB_WORKSPACE/fuckTodayStudy
          python3 index.py
