name: Upload Python Package

on:
  schedule:
    - cron: '20 13 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
      - name: Publish package
        run: 
          python ../../index.py
