name: Upload Python Package

on:
  schedule:
    - cron: '40 13 * * *'

jobs:
  Auto-Attendance:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Clone and SetUp pip
        run: |
          echo 'start clone'
          git clone https://github.com/ScottDemo/fuckTodayStudy.git
          cd fuckTodayStudy
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
      - name: Last Run
        run: 
          echo 'start running'
          python3 index.py
